
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    boolean edit =false;
    Vector<String>ID = new Vector<String>();
    Vector<Integer>qty = new Vector<Integer>();
    int totalOrder;
    int hargaburger =25000;
    int hargaayam =25000;
    int hargataco=35000;
    int harganachos=20000;
    int hargapizza=75000;
    int harganugget=15000;
    
    public Cart() {
        initComponents();
        setBounds(400, 100, 1500, 800);
    }
    public Cart(Vector<String>ID, Vector <Integer> qty,int totalOrder) {
        initComponents();
        setBounds(400, 100, 1500, 800);
        this.ID=ID;
        this.qty=qty;
        this.totalOrder=totalOrder;
        save.setVisible(false);
        Cancel.setVisible(false);
        
        DefaultTableModel table = (DefaultTableModel) TableJualan.getModel();
        table.setRowCount(this.totalOrder);
        for(int i = 0; i < totalOrder; i++){
            System.out.println(ID.get(i));
        }
        for (int i=0; i<this.totalOrder;i++){
            table.setValueAt(ID.get(i), i, 0);
            
            if(ID.get(i)=="FD01"){
                table.setValueAt("hamburger", i, 1);
                table.setValueAt(hargaburger, i, 2);
                
            }
            
            else if(ID.get(i)=="FD02"){
                table.setValueAt("Fried Chicken", i, 1);
                table.setValueAt(hargaayam, i, 2);
                
            }
            
            else if(ID.get(i)=="FD03"){
                table.setValueAt("Tacos", i, 1);
                table.setValueAt(hargataco, i, 2);
                
            }
            
            else if(ID.get(i)=="FD04"){
                table.setValueAt("Beef-Nachos", i, 1);
                table.setValueAt(harganachos, i, 2);
                
            }
            
            else if(ID.get(i)=="FD05"){
                table.setValueAt("Pepperoni-Pizza", i, 1);
                table.setValueAt(hargapizza, i, 2);
                
            }
            
            else if(ID.get(i)=="FD06"){
                table.setValueAt("Chicken Nugget", i, 1);
                table.setValueAt(harganugget, i, 2);
                
            }
        
                table.setValueAt(qty.get(i), i, 3);
        }  
        int grand = 0;
        int [] priceperitem = new int [6];
        for (int i=0;i<totalOrder;i++){
            if(ID.get(i).equals("FD01")){
                priceperitem[i] = qty.get(i) * hargaburger;
            }else if(ID.get(i).equals("FD02")){
                priceperitem[i] = qty.get(i) * hargaayam;
            }else if(ID.get(i).equals("FD03")){
                priceperitem[i] = qty.get(i) * hargataco;
            }else if(ID.get(i).equals("FD04")){
                priceperitem[i] = qty.get(i) * harganachos;
            }else if(ID.get(i).equals("FD05")){
                priceperitem[i] = qty.get(i) * hargapizza;
            }else if(ID.get(i).equals("FD06")){
                priceperitem[i] = qty.get(i) * harganugget;
            }
            
            grand += priceperitem[i];
        }
        Total.setText(String.valueOf(grand));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableJualan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDFood = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameFood = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GrandTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        TableJualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ));
        TableJualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableJualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableJualan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(147, 22, 33));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setBackground(new java.awt.Color(147, 22, 33));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("ID");
        jPanel4.add(jLabel1);

        IDFood.setForeground(new java.awt.Color(255, 255, 51));
        jPanel4.add(IDFood);

        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Name");
        jPanel4.add(jLabel2);

        NameFood.setForeground(new java.awt.Color(255, 255, 51));
        jPanel4.add(NameFood);

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Price");
        jPanel4.add(jLabel3);

        Price.setForeground(new java.awt.Color(255, 255, 51));
        jPanel4.add(Price);

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Quantity");
        jPanel4.add(jLabel4);
        jPanel4.add(Quantity);

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Total");
        jPanel4.add(jLabel5);

        Total.setForeground(new java.awt.Color(255, 255, 51));
        jPanel4.add(Total);

        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Grand Total");
        jPanel4.add(jLabel6);

        GrandTotal.setForeground(new java.awt.Color(255, 255, 51));
        jPanel4.add(GrandTotal);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(147, 22, 33));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel5.add(back);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel5.add(update);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel5.add(delete);

        pay.setText("Pay Now");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        jPanel5.add(pay);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel5.add(save);

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel5.add(Cancel);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.show();
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        edit=true;
        back.setVisible(false);
        update.setVisible(false);
        pay.setVisible(false);
        delete.setVisible(false);
        save.setVisible(true);
        Cancel.setVisible(true);        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        ID.removeElementAt(TableJualan.getSelectedRow());
        qty.removeElementAt(TableJualan.getSelectedRow());
        DefaultTableModel table = (DefaultTableModel) TableJualan.getModel();

        totalOrder--;
        table.setRowCount(totalOrder);
        
        for (int i =0;i<totalOrder;i++){
            table.setValueAt(ID.get(i), i, 0);
            if(ID.get(i)=="FD01"){
                table.setValueAt("hamburger", i, 1);
                table.setValueAt(hargaburger, i, 2);
                
            }
            
            else if(ID.get(i)=="FD02"){
                table.setValueAt("Fried Chicken", i, 1);
                table.setValueAt(hargaayam, i, 2);
                
            }
            
            else if(ID.get(i)=="FD03"){
                table.setValueAt("Tacos", i, 1);
                table.setValueAt(hargataco, i, 2);
                
            }
            
            else if(ID.get(i)=="FD04"){
                table.setValueAt("Beef-Nachos", i, 1);
                table.setValueAt(harganachos, i, 2);
                
            }
            
            else if(ID.get(i)=="FD05"){
                table.setValueAt("Pepperoni-Pizza", i, 1);
                table.setValueAt(hargapizza, i, 2);
                
            }
            
            else if(ID.get(i)=="FD06"){
                table.setValueAt("Chicken Nugget", i, 1);
                table.setValueAt(harganugget, i, 2);
                
            }
            
        }
        
        IDFood.setText("");
        NameFood.setText("");
        Price.setText("");
        Total.setText("");
        Quantity.setText("");
    }                                       

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Total.setText(String.valueOf(qty.get(TableJualan.getSelectedRow())));
        back.setVisible(true);
        update.setVisible(true);
        delete.setVisible(true);
        pay.setVisible(true);
        save.setVisible(false);
        Cancel.setVisible(false);
    }                                         

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
      
    }//GEN-LAST:event_deleteActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(null, "Are you sure finish from Ordering?", "Proceed Option", JOptionPane.YES_NO_OPTION);
        if(j == JOptionPane.YES_OPTION){
            ID.removeAllElements();
            qty.removeAllElements();
            DefaultTableModel table = (DefaultTableModel) TableJualan.getModel();
            totalOrder = 0;
            table.setRowCount(totalOrder);
            
            IDFood.setText(null);
            NameFood.setText(null);
            Price.setText(null);
            Total.setText(null);
            Total.setText(null);
            Total.setText(null);
            JOptionPane.showMessageDialog(rootPane, "Order Success!");
        } else{
            JOptionPane.showMessageDialog(rootPane, "Check your orders!");
        }
    }//GEN-LAST:event_payActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
          qty.set(TableJualan.getSelectedRow(), Integer.valueOf(Quantity.getText()));
        DefaultTableModel table = (DefaultTableModel) TableJualan.getModel();
        for(int i = 0; i < totalOrder; i++){
            table.setValueAt(qty.get(i), i, 3);
        }
        update.setVisible(true);
        back.setVisible(true);
        pay.setVisible(true);
        delete.setVisible(true);
        Cancel.setVisible(false);
        save.setVisible(false);

        
        
        int grand = 0;
        int [] priceperitem = new int [6];
        for (int i=0;i<totalOrder;i++){
            if(ID.get(i).equals("FD01")){
                priceperitem[i] = qty.get(i) * hargaburger;
            }else if(ID.get(i).equals("FD02")){
                priceperitem[i] = qty.get(i) * hargaayam;
            }else if(ID.get(i).equals("FD03")){
                priceperitem[i] = qty.get(i) * hargataco;
            }else if(ID.get(i).equals("FD04")){
                priceperitem[i] = qty.get(i) * harganachos;
            }else if(ID.get(i).equals("FD05")){
                priceperitem[i] = qty.get(i) * hargapizza;
            }else if(ID.get(i).equals("FD06")){
                priceperitem[i] = qty.get(i) * harganugget;
            }
            
            grand += priceperitem[i];
        }
        GrandTotal.setText(String.valueOf(grand));
        int totalsemua;
        totalsemua = Integer.valueOf(Price.getText()) * Integer.valueOf(Quantity.getText());
        Total.setText(String.valueOf(totalsemua));
        
        JOptionPane.showMessageDialog(rootPane, "Orders saved!");
    }//GEN-LAST:event_saveActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        Quantity.setText(String.valueOf(qty.get(TableJualan.getSelectedRow())));
        back.setVisible(true);
        update.setVisible(true);
        delete.setVisible(true);
        pay.setVisible(true);
        save.setVisible(false);
        Cancel.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void TableJualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableJualanMouseClicked
        // TODO add your handling code here:
        IDFood.setText(ID.get(TableJualan.getSelectedRow()));
        Quantity.setText(String.valueOf(qty.get(TableJualan.getSelectedRow())));
        
        if(ID.get(TableJualan.getSelectedRow()).equals("FD01")){
            NameFood.setText("Hamburger");
            Price.setText(String.valueOf(hargaburger));
            
        }
        
        else if(ID.get(TableJualan.getSelectedRow()).equals("FD02")){
            NameFood.setText("FriedChicken");
            Price.setText(String.valueOf(hargaayam));
        
        }
        
        else if(ID.get(TableJualan.getSelectedRow()).equals("FD03")){
            NameFood.setText("Tacos");
            Price.setText(String.valueOf(hargataco));
        
        }
        else if(ID.get(TableJualan.getSelectedRow()).equals("FD04")){
            NameFood.setText("Beef-Nachos");
            Price.setText(String.valueOf(harganachos));
        
        }
        else if(ID.get(TableJualan.getSelectedRow()).equals("FD05")){
            NameFood.setText("Pepperoni-Pizza");
            Price.setText(String.valueOf(hargapizza));
        
        }
        else if(ID.get(TableJualan.getSelectedRow()).equals("FD06")){
            NameFood.setText("Chicken Nugget with Ranch");
            Price.setText(String.valueOf(harganugget));
            
        
        }
        
        int totalsemua;
        totalsemua = Integer.valueOf(Price.getText()) * Integer.valueOf(Quantity.getText());
        Total.setText(String.valueOf(totalsemua));
        
    }//GEN-LAST:event_TableJualanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel GrandTotal;
    private javax.swing.JLabel IDFood;
    private javax.swing.JLabel NameFood;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTable TableJualan;
    private javax.swing.JLabel Total;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pay;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
