
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
     String user = "";
    String pw = "";
    public Register() {
        initComponents();
    
        setSize(1000,600);
        setLocationRelativeTo(null);
    }
 
      public void add_data (){
    user = UserField.getText();
    pw = PassField.getText();
    new Menu(user,pw).setVisible(true);
    this.setVisible(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        ConfPassField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBackground(new java.awt.Color(147, 22, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(109, 40));
        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 205, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTER");
        jLabel8.setMaximumSize(new java.awt.Dimension(109, 40));
        jLabel8.setMinimumSize(new java.awt.Dimension(109, 40));
        jLabel8.setPreferredSize(new java.awt.Dimension(109, 40));
        jPanel1.add(jLabel8);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(147, 22, 33));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 80));
        jPanel2.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 205, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");
        jPanel2.add(jLabel1);

        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UserField);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 205, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email");
        jPanel2.add(jLabel2);
        jPanel2.add(EmailField);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 205, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jPanel2.add(PassField);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 205, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Conf Pass");
        jPanel2.add(jLabel4);
        jPanel2.add(ConfPassField);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 205, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5);

        jPanel4.setBackground(new java.awt.Color(147, 22, 33));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        maleRadioBtn.setBackground(new java.awt.Color(147, 22, 33));
        buttonGroup1.add(maleRadioBtn);
        maleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        maleRadioBtn.setForeground(new java.awt.Color(255, 205, 0));
        maleRadioBtn.setText("Male");
        jPanel4.add(maleRadioBtn);

        femaleRadioBtn.setBackground(new java.awt.Color(147, 22, 33));
        buttonGroup1.add(femaleRadioBtn);
        femaleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        femaleRadioBtn.setForeground(new java.awt.Color(255, 205, 0));
        femaleRadioBtn.setText("Female");
        jPanel4.add(femaleRadioBtn);

        jPanel2.add(jPanel4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 205, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Phone");
        jPanel2.add(jLabel6);

        PhoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneFieldKeyTyped(evt);
            }
        });
        jPanel2.add(PhoneField);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 205, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address");
        jPanel2.add(jLabel7);
        jPanel2.add(AddressField);

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(147, 22, 33));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setBackground(new java.awt.Color(147, 22, 33));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jPanel3.add(jPanel5);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 205, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Copyright by Luki & Tama");
        jPanel3.add(jLabel9);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu log = new Menu();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String text = UserField.getText();
        boolean numeric=false;
        boolean alphabet=false;
        boolean etc=false;
        String password=PassField.getText();
        String Confirm=ConfPassField.getText();
        String angka = "(.*[0-9].*)";
        
        for(int i=0; i<password.length();i++){
            if(Character.isAlphabetic(password.charAt(i))){
                alphabet=true;
            }
             if(Character.isDigit(password.charAt(i))){
                numeric=true;
             }
         if(!Character.isAlphabetic(password.charAt(i))&&!Character.isDigit(password.charAt(i))){
             etc=true;
             break;
         }}
        
          if(UserField.getText().length()==0){
           JOptionPane.showMessageDialog(null,"Username must be filled!");
      }
          else if(text.length()<=3){
           JOptionPane.showMessageDialog(null,"Username must be more than 3 characters!");
       }
           else if (EmailField.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Email must be filled!”");
        }
        else if(!EmailField.getText().contains("@") &&(!EmailField.getText().contains(".com"))){
           JOptionPane.showMessageDialog(null,"Email must be valid!");
       } 
        else if(PassField.getText().length()==0){
           JOptionPane.showMessageDialog(null,"Password must be filled!");
      }
       
          
       else if(numeric==false || alphabet==false){
             JOptionPane.showMessageDialog(null,"Password must be alphanumeric!");
         
        }
        else if(ConfPassField.getText().length()==0){
           JOptionPane.showMessageDialog(null,"Confirm Password must be filled!");
      }
           else if(password.compareTo(Confirm)!=0){
                 JOptionPane.showMessageDialog(null,"Confirm Password must be equals to Password!");
                 ConfPassField.setText("");
        }  
        
           else if(!maleRadioBtn.isSelected()&& !femaleRadioBtn
                .isSelected() ){
            JOptionPane.showMessageDialog(null,"Gender must be selected!");
            return;
        }
           
           else if (PhoneField.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Phone Number must be filled");
           }
           else if (!PhoneField.getText().matches(angka)){
                   JOptionPane.showMessageDialog(null,"Phone Number must be Numeric!");
                }
           else if (AddressField.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Address must be filled!”");
           }
          else if(AddressField.getText().length()<=8){
           JOptionPane.showMessageDialog(null,"Address must be more than 8 characters!");
           
       }
          else {
              JOptionPane.showMessageDialog(null, "Success register account");
              add_data();
                     
          }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int n= JOptionPane.showConfirmDialog(null,"Are you sure you want to reset?","WARNING"
        ,JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            UserField.setText("");
            EmailField.setText("");
            PassField.setText("");
            ConfPassField.setText("");
           buttonGroup1.clearSelection();
            AddressField.setText("");
            PhoneField.setText("");
            AddressField.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null,"You didn't select yes!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PhoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneFieldKeyTyped
        // TODO add your handling code here

    }//GEN-LAST:event_PhoneFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JPasswordField ConfPassField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JTextField UserField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton maleRadioBtn;
    // End of variables declaration//GEN-END:variables
}
