
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JOptionPane;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaListPlayerComponent;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Video extends javax.swing.JFrame {
    
     EmbeddedMediaListPlayerComponent video ;
     boolean videoIsPlaying = true;
    /**
     * Creates new form Video
     */
    public Video() {
        initComponents();
        setBounds(10, 10, 400, 400);
        try {
              NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), 
       "C:\\Program Files\\VideoLAN\\VLC");
              try {
                  NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), 
       "C:\\Program Files (x86)\\VideoLAN\\VLC");
              } catch (Exception ee) {
              }
        } catch (Exception e) {
                              JOptionPane.showConfirmDialog(null, "VLC blum terinstall");

        }//untuk path open file loc aja
        //load library vlcnya
        Native.load(RuntimeUtil.getLibVlcLibraryName() ,LibVlc.class);
          //1.insttantiate video
        video = new EmbeddedMediaListPlayerComponent();
        //2. prepare media
        video.getMediaPlayer().prepareMedia(new File("Assets/video.mp4").getAbsolutePath());
        //add video ke frame kita
        add(video, new BorderLayout().CENTER);
        //video bakal langsung maen pas kita jalankan
        video.getMediaPlayer().start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Video().setVisible(true);
            }
        });
    }

    private void setLocationRelativeTo(float RIGHT_ALIGNMENT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
